.PHONY: build build-web build-go dev dev-api dev-web docker clean dolt generate seed test test-go test-web test-e2e lint lint-go lint-web update-screenshots update-screenshots-web update-screenshots-e2e docs

# Generate TypeScript types from Go structs
# Tygo generates per-domain files, then we assemble them into the two barrel files
# that the Angular frontend imports from ($generated/models, $generated/user-models).
GEN_DIR := web/src/app/generated
generate:
	go run github.com/gzuidhof/tygo@latest generate
	@# Assemble models barrel (models.ts) — exercise, equipment, groups, relationships, fulfillments
	@{ \
		echo '// Code generated by tygo. DO NOT EDIT.'; \
		for f in $(GEN_DIR)/shared.ts $(GEN_DIR)/exercise.ts $(GEN_DIR)/equipment.ts $(GEN_DIR)/exercise-group.ts $(GEN_DIR)/exercise-relationship.ts $(GEN_DIR)/equipment-fulfillment.ts $(GEN_DIR)/equipment-relationship.ts; do \
			tail -n +2 "$$f"; \
		done; \
	} | sed 's/shared\.BaseModel/BaseModel/g' > $(GEN_DIR)/models.ts
	@# Assemble user-models barrel (user-models.ts) — workouts, workout logs, exercise logs
	@{ \
		echo '// Code generated by tygo. DO NOT EDIT.'; \
		echo ''; \
		echo '//////////'; \
		echo '// source: base.go'; \
		echo ''; \
		echo 'export interface BaseModel {'; \
		echo '  id: number /* uint */;'; \
		echo '  createdAt: string;'; \
		echo '  updatedAt: string;'; \
		echo '  deletedAt?: string | null;'; \
		echo '}'; \
		echo 'export interface ErrorResponse {'; \
		echo '  error: string;'; \
		echo '}'; \
		for f in $(GEN_DIR)/user-workout.ts $(GEN_DIR)/user-exerciselog.ts $(GEN_DIR)/user-workoutlog.ts; do \
			tail -n +2 "$$f"; \
		done; \
	} | sed -e 's/shared\.BaseModel/BaseModel/g' -e 's/any \/\* workoutmodels\.WorkoutSectionType \*\//WorkoutSectionType/g' -e 's/any \/\* exerciselogmodels\.ExerciseLog \*\//ExerciseLog/g' > $(GEN_DIR)/user-models.ts
	@# Clean up intermediate files
	@rm -f $(GEN_DIR)/shared.ts $(GEN_DIR)/exercise.ts $(GEN_DIR)/equipment.ts $(GEN_DIR)/exercise-group.ts $(GEN_DIR)/exercise-relationship.ts $(GEN_DIR)/equipment-fulfillment.ts $(GEN_DIR)/equipment-relationship.ts $(GEN_DIR)/user-workout.ts $(GEN_DIR)/user-workoutlog.ts $(GEN_DIR)/user-exerciselog.ts
	@cd web && npx prettier --write 'src/app/generated/*.ts' > /dev/null 2>&1 || true

# Full production build: generate types → Angular → Go binary with embedded SPA
build: generate build-web build-go

build-web:
	cd web && npm install && npx ng build --configuration=production

build-go: build-web
	go build -o gesitr .

# Development: start Go API + Angular dev server together
dev: generate docs
	./scripts/dev.sh

dev-api:
	DEV=true AUTH_FALLBACK_USER=anon go run .

dev-web: generate
	cd web && CI=true npx ng serve

dolt:
	dolt sql-server --host 127.0.0.1 --port 3307 --data-dir .beads/dolt

# Lint and format check
lint: lint-go lint-web

lint-go:
	@test -z "$$(gofmt -l .)" || (echo "Go files not formatted:" && gofmt -l . && exit 1)

lint-web:
	cd web && npm run lint && npm run format:check

# Run all tests
test: lint test-go test-web test-e2e

test-go:
	go test ./...

test-web:
	cd web && npm test

# E2E uses dedicated ports to avoid conflicts with dev servers (8080/4200).
# API on :9876, Angular on :4300 (configured in angular.json serve:e2e + proxy.e2e.conf.json).
E2E_API_PORT := 9876

# E2E tests: builds Go binary, starts API on dedicated port, runs ng e2e (which manages
# its own Angular dev server via the "isolated" configuration), then cleans up.
test-e2e:
	@rm -f .gesitr-e2e
	@go build -o .gesitr-e2e .
	@echo "Starting API server on :$(E2E_API_PORT)..."
	@DATABASE_PATH=:memory: DEV=true AUTH_FALLBACK_USER=anon PORT=$(E2E_API_PORT) ./.gesitr-e2e & \
		API_PID=$$!; \
		for i in 1 2 3 4 5 6 7 8 9 10; do \
			curl -sf http://localhost:$(E2E_API_PORT)/api/exercises > /dev/null 2>&1 && break; \
			sleep 1; \
		done; \
		cd web && npx ng e2e --configuration=isolated; \
		TEST_EXIT=$$?; \
		kill $$API_PID 2>/dev/null; wait $$API_PID 2>/dev/null; \
		rm -f ../.gesitr-e2e; \
		exit $$TEST_EXIT

# Update screenshot baselines — same server setup as test-e2e.
update-screenshots: update-screenshots-web update-screenshots-e2e

update-screenshots-web:
	find web/src/app -path '*__screenshots__*' -name '*.png' -delete
	cd web && npx ng run web:test-screenshot || true
	cd web && npx ng run web:test-screenshot

update-screenshots-e2e:
	@rm -f .gesitr-e2e
	@go build -o .gesitr-e2e .
	@echo "Starting API server on :$(E2E_API_PORT)..."
	@DATABASE_PATH=:memory: DEV=true AUTH_FALLBACK_USER=anon PORT=$(E2E_API_PORT) ./.gesitr-e2e & \
		API_PID=$$!; \
		for i in 1 2 3 4 5 6 7 8 9 10; do \
			curl -sf http://localhost:$(E2E_API_PORT)/api/exercises > /dev/null 2>&1 && break; \
			sleep 1; \
		done; \
		cd web && npx ng e2e --configuration=isolated --update-snapshots; \
		TEST_EXIT=$$?; \
		kill $$API_PID 2>/dev/null; wait $$API_PID 2>/dev/null; \
		rm -f ../.gesitr-e2e; \
		exit $$TEST_EXIT

docker:
	docker build --build-arg CACHEBUST=$$(date +%s) -t gesitr .

seed:
	rm -f gesitr.db
	go run ./cmd/seed

clean:
	rm -f gesitr gesitr.db
	rm -rf web/dist
	rm -f web/src/app/generated/models.ts

docs:
	./scripts/docs.sh
